"""add_project_achievements_table

Revision ID: 1615f0bbecd1
Revises: a446493d9b5c
Create Date: 2025-09-10 12:53:09.744885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1615f0bbecd1'
down_revision = 'a446493d9b5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_achievements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_achievements_id'), 'project_achievements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_achievements_id'), table_name='project_achievements')
    op.drop_table('project_achievements')
    # ### end Alembic commands ###
