"""Add latex_s3_key column to resume_versions

Revision ID: add_latex_s3_key_resume_versions
Revises: add_s3_key_resume_versions
Create Date: 2025-09-25 12:45:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_latex_s3_key_resume_versions'
down_revision = 'add_s3_key_resume_versions'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('latex_s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 'latex_s3_key')
    # ### end Alembic commands ###
