"""Add s3_key column to resume_versions

Revision ID: add_s3_key_resume_versions
Revises: 22e67c0fb921
Create Date: 2025-09-25 12:42:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_s3_key_resume_versions'
down_revision = '22e67c0fb921'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resume_versions', sa.Column('s3_key', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resume_versions', 's3_key')
    # ### end Alembic commands ###
