"""Add password hash to users table

Revision ID: 692c0bcb96b5
Revises: d3f648f82ac0
Create Date: 2025-09-05 23:28:09.033328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692c0bcb96b5'
down_revision = 'd3f648f82ac0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
